# Generated by Django 4.1.13 on 2025-12-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Immobilier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix', models.FloatField()),
                ('surface', models.FloatField()),
                ('region', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('gouvernorat', models.CharField(max_length=100)),
                ('fonctionnalite', models.CharField(max_length=200)),
                ('datePublication', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(max_length=50)),
            ],
        ),
    ]
