# Generated by Django 4.1.13 on 2025-12-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('siteWeb', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immobilierId', models.IntegerField()),
                ('visiteurId', models.IntegerField()),
                ('adminId', models.IntegerField()),
                ('dateSouhaitee', models.DateField()),
                ('dateConfirmee', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(max_length=50)),
            ],
        ),
    ]
