# Generated by Django 4.1.13 on 2025-12-07 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_agence_visite'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspaceTravail',
            fields=[
                ('immobilier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='annonces.immobilier')),
                ('superficie', models.FloatField()),
                ('nombrePieces', models.IntegerField()),
                ('typeActivite', models.CharField(max_length=100)),
                ('internetDisponible', models.BooleanField(default=False)),
                ('vitrine', models.BooleanField(default=False)),
            ],
            bases=('annonces.immobilier',),
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('immobilier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='annonces.immobilier')),
                ('nombreEtages', models.IntegerField()),
                ('nombreChambres', models.IntegerField()),
                ('nombreSallesDeBain', models.IntegerField()),
                ('balcon', models.BooleanField(default=False)),
                ('garage', models.BooleanField(default=False)),
                ('piscine', models.BooleanField(default=False)),
            ],
            bases=('annonces.immobilier',),
        ),
        migrations.CreateModel(
            name='PlaceDeParc',
            fields=[
                ('immobilier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='annonces.immobilier')),
                ('type', models.CharField(max_length=100)),
                ('securite', models.BooleanField(default=False)),
            ],
            bases=('annonces.immobilier',),
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('immobilier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='annonces.immobilier')),
                ('superficie', models.FloatField()),
                ('constructible', models.BooleanField(default=False)),
                ('titreFoncier', models.CharField(max_length=200)),
            ],
            bases=('annonces.immobilier',),
        ),
        migrations.RemoveField(
            model_name='visite',
            name='immobilierId',
        ),
        migrations.AddField(
            model_name='visite',
            name='immobilier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='annonces.immobilier'),
            preserve_default=False,
        ),
    ]
