# Generated by Django 4.1.13 on 2025-12-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_espacetravail_logement_placedeparc_terrain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='immobilier',
            name='approuve',
            field=models.BooleanField(default=False),
        ),
    ]
