# Generated by Django 3.1.12 on 2026-01-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0005_auto_20251210_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='immobilier',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
