# Generated by Django 3.1.12 on 2026-01-13 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0006_immobilier_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immobilier',
            name='image',
        ),
        migrations.CreateModel(
            name='ImageImmobilier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('ordre', models.IntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('immobilier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='annonces.immobilier')),
            ],
            options={
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
    ]
