# Generated by Django 3.1.12 on 2026-01-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0007_auto_20260113_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='immobilier',
            name='type_bien',
            field=models.CharField(choices=[('Immobilier', 'Immobilier'), ('Logement', 'Logement'), ('Terrain', 'Terrain'), ('Espace de travail', 'Espace de travail'), ('Place de parc', 'Place de parc')], default='Immobilier', max_length=50),
        ),
    ]
