# Generated by Django 3.1.12 on 2026-02-02 19:14

import annonces.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0008_immobilier_type_bien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageimmobilier',
            name='image',
            field=models.ImageField(upload_to=annonces.models.image_upload_path),
        ),
    ]
