# Generated by Django 4.1.13 on 2025-12-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('validation', 'Validation'), ('visite', 'Visite'), ('favori', 'Favori')], max_length=20)),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(max_length=20)),
                ('adminId', models.IntegerField()),
                ('ownerId', models.IntegerField()),
            ],
        ),
    ]
