# Generated by Django 3.1.12 on 2026-02-02 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annonces', '0009_auto_20260202_2014'),
        ('notifications', '0002_auto_20251210_0139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='adminId',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='ownerId',
        ),
        migrations.AddField(
            model_name='notification',
            name='annonce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annonces.immobilier'),
        ),
        migrations.AddField(
            model_name='notification',
            name='destinataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_recues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='statut',
            field=models.CharField(choices=[('non_lu', 'Non lu'), ('lu', 'Lu')], default='non_lu', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('nouvelle_annonce', 'Nouvelle Annonce'), ('annonce_approuvee', 'Annonce Approuvée'), ('annonce_rejetee', 'Annonce Rejetée'), ('visite', 'Visite')], max_length=30),
        ),
    ]
