"""
Django settings for ameniimmo project.

Generated by 'django-admin startproject' using Django 4.1.13.
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-%thgpz#2zv4j##q-9+#=zxv$oak($jzcc^cre)f%j$--i%eoh5')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = ["*"]  # ✅ autorise toutes les connexions en dev

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # ✅ Apps externes
    'rest_framework',
    'corsheaders',

    # ✅ Apps internes
    'users',
    'annonces',
    'notifications',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    # ✅ CORS pour autoriser le frontend
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ameniimmo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # ✅ si tu veux ajouter des templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ameniimmo.wsgi.application'

# ✅ Base de données : MongoDB Atlas via djongo
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'CLIENT': {
            'host': config('MONGODB_URI'),
            'name': config('MONGODB_DB_NAME', default='ameniimmo_db'),
            'authMechanism': 'SCRAM-SHA-1',
        }
    }
}

# ✅ Authentification : utilisation du modèle Utilisateur personnalisé
AUTH_USER_MODEL = 'users.Utilisateur'

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},  # ✅ mot de passe minimum 8 caractères
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'fr'  # ✅ langue par défaut en français
TIME_ZONE = 'Africa/Tunis'  # ✅ fuseau horaire Tunisie
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ✅ Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        # Ajout de l'authentification JWT (utilisée par le frontend)
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

# ✅ CORS configuration (autorise ton frontend Angular/React)
CORS_ALLOW_ALL_ORIGINS = True


#######################################################################################

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]  # ✅ crée ce dossier manuellement

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# ✅ Authentification : utilisation du modèle Utilisateur personnalisé
AUTH_USER_MODEL = 'users.Utilisateur'
