"""
Django settings for ameniimmo project.

Generated by 'django-admin startproject' using Django 4.1.13.
"""

from pathlib import Path
from decouple import config
import ssl
import certifi
import cloudinary

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-%thgpz#2zv4j##q-9+#=zxv$oak($jzcc^cre)f%j$--i%eoh5')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = ["*"]  # ✅ autorise toutes les connexions en dev

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # ✅ Apps externes
    'cloudinary_storage',
    'cloudinary',
    'rest_framework',
    'corsheaders',

    # ✅ Apps internes
    'users',
    'annonces',
    'notifications',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # ✅ Pour servir les fichiers statiques
    'django.contrib.sessions.middleware.SessionMiddleware',

    # ✅ CORS pour autoriser le frontend
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ameniimmo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # ✅ si tu veux ajouter des templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ameniimmo.wsgi.application'

# ✅ Base de données : Configuration avec SQLite (dev) et MongoDB (production)
# Changez USE_SQLITE = False quand vous aurez Python 3.10
USE_SQLITE = config('USE_SQLITE', default=True, cast=bool)

if USE_SQLITE:
    # SQLite pour développement local (évite le problème SSL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # MongoDB Atlas via djongo (nécessite Python 3.10)
    DATABASES = {
        'default': {
            'ENGINE': 'djongo',
            'CLIENT': {
                'host': config('MONGODB_URI'),
                'name': config('MONGODB_DB_NAME', default='ameniimmo_db'),
                'authMechanism': 'SCRAM-SHA-1',
                'tlsAllowInvalidCertificates': True,
            }
        }
    }

# ✅ Authentification : utilisation du modèle Utilisateur personnalisé
AUTH_USER_MODEL = 'users.Utilisateur'

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},  # ✅ mot de passe minimum 8 caractères
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'fr'  # ✅ langue par défaut en français
TIME_ZONE = 'Africa/Tunis'  # ✅ fuseau horaire Tunisie
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # ✅ Pour la production
STATICFILES_DIRS = [BASE_DIR / "static"]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'  # ✅ Optimisation

# ✅ Configuration Cloudinary pour le stockage des images
cloudinary.config(
    cloud_name = config('CLOUDINARY_CLOUD_NAME', default=''),
    api_key = config('CLOUDINARY_API_KEY', default=''),
    api_secret = config('CLOUDINARY_API_SECRET', default=''),
    secure = True
)

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME', default=''),
    'API_KEY': config('CLOUDINARY_API_KEY', default=''),
    'API_SECRET': config('CLOUDINARY_API_SECRET', default=''),
}

# Utiliser Cloudinary pour les media files
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ✅ Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        # Ajout de l'authentification JWT (utilisée par le frontend)
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

# ✅ CORS configuration
CORS_ALLOW_ALL_ORIGINS = True  # Pour déploiement rapide
# Alternative sécurisée : liste les domaines exacts
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "https://ameni-immo.vercel.app",
# ]
CORS_ALLOW_CREDENTIALS = True

# ✅ JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=5),  # Token valide 5 heures
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Refresh token valide 7 jours
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}

# ✅ Authentification : utilisation du modèle Utilisateur personnalisé
AUTH_USER_MODEL = 'users.Utilisateur'
